if not mods["5dim_logistic"] then return end 

data.raw.recipe["5d-logistic-robot-02"].category = "robotics"
data.raw.recipe["5d-logistic-robot-03"].category = "robotics"
data.raw.recipe["5d-logistic-robot-04"].category = "robotics"
data.raw.recipe["5d-logistic-robot-05"].category = "robotics"
data.raw.recipe["5d-logistic-robot-06"].category = "robotics"
data.raw.recipe["5d-logistic-robot-07"].category = "robotics"
data.raw.recipe["5d-logistic-robot-08"].category = "robotics"
data.raw.recipe["5d-logistic-robot-09"].category = "robotics"
data.raw.recipe["5d-logistic-robot-10"].category = "robotics"

data.raw.recipe["5d-construction-robot-02"].category = "robotics"
data.raw.recipe["5d-construction-robot-03"].category = "robotics"
data.raw.recipe["5d-construction-robot-04"].category = "robotics"
data.raw.recipe["5d-construction-robot-05"].category = "robotics"
data.raw.recipe["5d-construction-robot-06"].category = "robotics"
data.raw.recipe["5d-construction-robot-07"].category = "robotics"
data.raw.recipe["5d-construction-robot-08"].category = "robotics"
data.raw.recipe["5d-construction-robot-09"].category = "robotics"
data.raw.recipe["5d-construction-robot-10"].category = "robotics"

data.raw.recipe["5d-roboport-03"].category = "robotics"
data.raw.recipe["5d-roboport-04"].category = "robotics"
data.raw.recipe["5d-roboport-05"].category = "robotics"
data.raw.recipe["5d-roboport-06"].category = "robotics"
data.raw.recipe["5d-roboport-07"].category = "robotics"
data.raw.recipe["5d-roboport-08"].category = "robotics"
data.raw.recipe["5d-roboport-09"].category = "robotics"
data.raw.recipe["5d-roboport-10"].category = "robotics"