if not mods["5dim_transport"] then return end 

data.raw.recipe["5d-inserter-03"].category = "robotics"
data.raw.recipe["5d-inserter-04"].category = "robotics"
data.raw.recipe["5d-inserter-05"].category = "robotics"
data.raw.recipe["5d-inserter-06"].category = "robotics"
data.raw.recipe["5d-inserter-07"].category = "robotics"
data.raw.recipe["5d-inserter-08"].category = "robotics"
data.raw.recipe["5d-inserter-09"].category = "robotics"
data.raw.recipe["5d-inserter-10"].category = "robotics"

data.raw.recipe["5d-bulk-inserter-02"].category = "robotics"
data.raw.recipe["5d-bulk-inserter-03"].category = "robotics"
data.raw.recipe["5d-bulk-inserter-04"].category = "robotics"
data.raw.recipe["5d-bulk-inserter-05"].category = "robotics"
data.raw.recipe["5d-bulk-inserter-06"].category = "robotics"
data.raw.recipe["5d-bulk-inserter-07"].category = "robotics"
data.raw.recipe["5d-bulk-inserter-08"].category = "robotics"
data.raw.recipe["5d-bulk-inserter-09"].category = "robotics"
data.raw.recipe["5d-bulk-inserter-10"].category = "robotics"

data.raw.recipe["5d-stack-inserter-02"].category = "robotics"
data.raw.recipe["5d-stack-inserter-03"].category = "robotics"
data.raw.recipe["5d-stack-inserter-04"].category = "robotics"
data.raw.recipe["5d-stack-inserter-05"].category = "robotics"
data.raw.recipe["5d-stack-inserter-06"].category = "robotics"
data.raw.recipe["5d-stack-inserter-07"].category = "robotics"
data.raw.recipe["5d-stack-inserter-08"].category = "robotics"
data.raw.recipe["5d-stack-inserter-09"].category = "robotics"
data.raw.recipe["5d-stack-inserter-10"].category = "robotics"